# Generated by Django 4.0.2 on 2022-02-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='followers',
            new_name='followers_number',
        ),
    ]
